name: Markdown to PDF

on: 
  push:
    branches:
      - main

jobs:
  check-spell: 
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.48.0
      name: Spellcheck
      with:
        source_files: cv_files/CV.md
        task_name: Markdown
  converttopdf:
    name: Buid PDF
    runs-on: ubuntu-latest
    outputs:
      versioned_name: ${{ steps.set-version.outputs.version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set version name
        id: set-version
        run: |
          echo "version=cv_files-$(date +'%Y-%m-%d')-${{ github.run_number }}" >> $GITHUB_OUTPUT
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: cv_files
          output_dir: pdf
          built_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-version.outputs.version }}
          path: pdf
          